# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: ubuntu-latest
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  sdkDotnetVersion: '5.x'
  rootDir: 'Tailspin.SpaceGame.Web/wwwroot'

steps:
- task: UseDotNet@2
  inputs:
    version: '$(sdkDotnetVersion)'

- task: Npm@1
  displayName: 'Install npm'
  inputs:
   verbose: false

- script: './node_modules/.bin/node-sass $(rootDir) --output $(rootDir)'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.BuildId), $(Build.DefinitionName), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'write build info'
  workingDirectory: '$(rootdir)'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  
- template: templates/build.yml
  parameters:
    buildConfiguration: 'build'
    
- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
    

- task: PublishBuildArtifacts@1
  displayName: 'publish artifact'
  condition: Succeeded()
  inputs:
    ArtifactName: 'build'
