parameters:
  buildConfiguration: 'Release'
  sdkVersion: '5.x'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build pipeline'
  inputs: 
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'
    

- task: DotNetCoreCLI@2
  displayName: 'Publish project ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/$ {{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'
    publishWebProjects: false
    zipAfterPublish: True

